// Sample biodata results
export const biodatas = [
    {
        id: "BD001",
        name: "Fatima Rahman",
        age: 25,
        gender:"male",
        profession: "Software Engineer",
        education: "BSc in Computer Science",
        location: "Dhaka, Bangladesh",
        maritalStatus: "Never married",
        height: "5'4\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD002",
        gender:"male",
        name: "Ahmed Hassan",
        age: 28,
        profession: "Doctor",
        education: "MBBS",
        location: "Chittagong, Bangladesh",
        maritalStatus: "Never married",
        height: "5'8\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD003",
        name: "Ayesha Khan",
        gender:"male",
        age: 23,
        profession: "Teacher",
        education: "MA in English",
        location: "Sylhet, Bangladesh",
        maritalStatus: "Never married",
        height: "5'3\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD004",
        name: "Mohammad Ali",
        gender:"male",
        age: 30,
        profession: "Business Owner",
        education: "MBA",
        location: "Dhaka, Bangladesh",
        maritalStatus: "Divorced",
        height: "5'10\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD005",
        gender:"male",
        name: "Zara Ahmed",
        age: 26,
        profession: "Graphic Designer",
        education: "BFA",
        location: "Rajshahi, Bangladesh",
        maritalStatus: "Never married",
        height: "5'5\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD006",
        gender:"male",
        name: "Omar Farooq",
        age: 32,
        profession: "Engineer",
        education: "BSc in Civil Engineering",
        location: "Khulna, Bangladesh",
        maritalStatus: "Widower",
        height: "5'9\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD007",
        gender:"male",
        name: "Nadia Islam",
        age: 24,
        profession: "Nurse",
        education: "BSc in Nursing",
        location: "Dhaka, Bangladesh",
        maritalStatus: "Never married",
        height: "5'2\"",
        image: "/placeholder.svg?height=150&width=150",
    },
    {
        id: "BD008",
        gender:"male",
        name: "Tariq Rahman",
        age: 29,
        profession: "Banker",
        education: "BBA",
        location: "Chittagong, Bangladesh",
        maritalStatus: "Never married",
        height: "5'7\"",
        image: "/placeholder.svg?height=150&width=150",
    },
]